-- Remote notices shown by installed clients without publishing a new version.
-- Data API access is intentionally explicit because new public tables may not
-- be auto-exposed on current Supabase projects.

create table if not exists public.remote_notices (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  notice_key text not null,
  title text not null,
  message text not null,
  events text[] not null,
  active boolean not null default true,
  starts_at timestamptz,
  ends_at timestamptz,
  button_text text,
  button_url text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint remote_notices_notice_key_unique unique (user_id, notice_key),
  constraint remote_notices_events_not_empty check (cardinality(events) > 0),
  constraint remote_notices_known_events check (
    events <@ array['abrir_caja', 'cerrar_caja']::text[]
  ),
  constraint remote_notices_button_pair check (
    (button_text is null and button_url is null)
    or (button_text is not null and button_url is not null)
  )
);

create index if not exists remote_notices_user_active_idx
  on public.remote_notices (user_id, active);

create index if not exists remote_notices_validity_idx
  on public.remote_notices (starts_at, ends_at);

create index if not exists remote_notices_events_idx
  on public.remote_notices using gin (events);

grant select on table public.remote_notices to authenticated;
grant insert, update, delete on table public.remote_notices to authenticated;
grant select, insert, update, delete on table public.remote_notices to service_role;
grant usage, select on sequence public.remote_notices_id_seq to authenticated, service_role;

alter table public.remote_notices enable row level security;

drop policy if exists "Stores view active remote notices" on public.remote_notices;
create policy "Stores view active remote notices"
on public.remote_notices
for select
to authenticated
using (
  (select auth.uid()) is not null
  and (select auth.uid()) = user_id
  and active = true
  and (starts_at is null or starts_at <= now())
  and (ends_at is null or ends_at >= now())
);

drop policy if exists "Super admins manage remote notices" on public.remote_notices;
create policy "Super admins manage remote notices"
on public.remote_notices
for all
to authenticated
using ((select public.is_super_admin()))
with check ((select public.is_super_admin()));

insert into public.remote_notices (
  user_id,
  notice_key,
  title,
  message,
  events,
  active,
  starts_at,
  button_text,
  button_url
)
select
  p.id,
  'licencia-proxima-vencer-canotal-express',
  'Licencia próxima a vencer',
  'Hola recuerda que tu licencia esta próxima a vencer, favor de contactar a tu administrador de cuenta y evites suspensión.',
  array['abrir_caja', 'cerrar_caja']::text[],
  true,
  now(),
  'Contactar por WhatsApp',
  'https://wa.me/5215650607108'
from public.profiles p
where p.store_name ilike '%Cañotal%'
   or p.store_name ilike '%Canotal%'
   or p.store_name ilike '%Cañotal Express%'
   or p.store_name ilike '%Canotal Express%'
on conflict (user_id, notice_key) do update
set
  title = excluded.title,
  message = excluded.message,
  events = excluded.events,
  active = excluded.active,
  starts_at = excluded.starts_at,
  ends_at = excluded.ends_at,
  button_text = excluded.button_text,
  button_url = excluded.button_url,
  updated_at = now();
