-- ========================================================
-- MIGRACIÓN: SISTEMA DE DELIVERY Y RECOGIDA DE ROPA
-- ========================================================

-- 1. Modificar tabla public.profiles para configuración de pasarela
alter table public.profiles
add column if not exists whatsapp_gateway_type text default 'central_saas',
add column if not exists whatsapp_session_token text;

-- 2. Crear tabla de clientes (public.customers)
create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  name text not null,
  phone text not null,
  address text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS en public.customers
alter table public.customers enable row level security;

-- Política de RLS para public.customers
create policy "Users can CRUD own customers" on public.customers
  for all using (auth.uid() = user_id);

-- 3. Crear tabla de pedidos de delivery (public.delivery_orders)
create table if not exists public.delivery_orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null default auth.uid(),
  customer_id uuid references public.customers(id) on delete set null,
  customer_name text not null,
  customer_phone text not null,
  customer_address text not null,
  notes text,
  driver_id bigint references public.staff(id) on delete set null,
  status text not null default 'requested',
  garment_summary text,
  service_cost numeric(10,2) not null default 0.00,
  delivery_fee numeric(10,2) not null default 0.00,
  tracking_token uuid not null default gen_random_uuid(),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  accepted_at timestamp with time zone,
  picked_up_at timestamp with time zone,
  delivered_to_store_at timestamp with time zone,
  completed_at timestamp with time zone
);

-- Habilitar RLS en public.delivery_orders
alter table public.delivery_orders enable row level security;

-- Políticas de RLS para public.delivery_orders
create policy "Stores can CRUD own delivery orders" on public.delivery_orders
  for all using (auth.uid() = user_id);

create policy "Anyone can read order by tracking token" on public.delivery_orders
  for select using (true);

-- 4. Habilitar publicación Realtime
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (
      select 1 
      from pg_publication_rel pr 
      join pg_class c on pr.prrelid = c.oid 
      join pg_namespace n on c.relnamespace = n.oid 
      where pr.prpubid = (select oid from pg_publication where pubname = 'supabase_realtime')
      and n.nspname = 'public' 
      and c.relname = 'delivery_orders'
    ) then
      alter publication supabase_realtime add table public.delivery_orders;
    end if;
  end if;
end $$;
