-- Tabla: Registro diario de produccion por empleado (Planilla YAIR)
-- Replica la logica del ODS: notas/tickets por staff con kg, tintoreria, cobertores, etc.
-- Soporta carga hibrida: desde ordenes POS + entrada manual

CREATE TABLE IF NOT EXISTS public.daily_production_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL DEFAULT auth.uid(),
  entry_date DATE NOT NULL,
  staff_id BIGINT REFERENCES public.staff(id) ON DELETE CASCADE,
  nota TEXT,
  kg_lavado NUMERIC(10,2) DEFAULT 0,
  tintoreria INTEGER DEFAULT 0,
  cobertores INTEGER DEFAULT 0,
  prenda_extra INTEGER DEFAULT 0,
  gorras INTEGER DEFAULT 0,
  tennis INTEGER DEFAULT 0,
  mochila_bolsa INTEGER DEFAULT 0,
  planchado INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, entry_date, staff_id, nota)
);

COMMENT ON TABLE public.daily_production_entries IS 'Registro diario de produccion por empleado - planilla tipo YAIR.ods';
COMMENT ON COLUMN public.daily_production_entries.nota IS 'Numero de ticket/folio de la orden';
COMMENT ON COLUMN public.daily_production_entries.kg_lavado IS 'Kilos de ropa lavada (lavanderia)';
COMMENT ON COLUMN public.daily_production_entries.tintoreria IS 'Cantidad de prendas procesadas en tintoreria';
COMMENT ON COLUMN public.daily_production_entries.cobertores IS 'Cantidad de cobertores/edredones procesados';
COMMENT ON COLUMN public.daily_production_entries.prenda_extra IS 'Prendas extra procesadas';

-- Indices
CREATE INDEX IF NOT EXISTS idx_daily_prod_user_date ON public.daily_production_entries(user_id, entry_date);
CREATE INDEX IF NOT EXISTS idx_daily_prod_staff ON public.daily_production_entries(staff_id);

-- RLS: solo el dueno ve sus entradas
ALTER TABLE public.daily_production_entries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users CRUD own production entries"
  ON public.daily_production_entries FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Feature flag en business_settings
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'business_settings'
      AND column_name = 'daily_production_enabled'
  ) THEN
    ALTER TABLE public.business_settings
    ADD COLUMN daily_production_enabled BOOLEAN DEFAULT false;
    COMMENT ON COLUMN public.business_settings.daily_production_enabled
    IS 'Habilita la planilla diaria de produccion por empleado (tipo YAIR.ods)';
  END IF;
END $$;
