-- ========================================================
-- PREFERENCIA DE PAGO Y ABONOS EN DELIVERY
-- ========================================================

alter table public.delivery_orders
add column if not exists payment_preference text,
add column if not exists payment_preference_confirmed_at timestamptz,
add column if not exists customer_item_description text,
add column if not exists payment_status text not null default 'unpaid',
add column if not exists pos_order_id bigint,
add column if not exists completed_with_balance boolean not null default false;

create table if not exists public.delivery_payments (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  delivery_order_id bigint references public.delivery_orders(id) on delete cascade not null,
  driver_id bigint references public.staff(id) on delete set null,
  amount numeric(10,2) not null check (amount > 0),
  payment_method text not null check (payment_method in ('efectivo', 'transferencia', 'tarjeta')),
  reference text,
  status text not null default 'driver_collected' check (status in ('driver_collected', 'reconciled', 'voided')),
  receipt_token uuid not null default gen_random_uuid(),
  receipt_sent_at timestamptz,
  reconciled_at timestamptz,
  created_at timestamptz not null default timezone('utc'::text, now())
);

alter table public.delivery_payments enable row level security;

create policy "Stores can CRUD own delivery payments" on public.delivery_payments
  for all using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create index if not exists idx_delivery_payments_order on public.delivery_payments(delivery_order_id);
create index if not exists idx_delivery_payments_receipt_token on public.delivery_payments(receipt_token);

alter table public.delivery_orders
drop constraint if exists delivery_orders_payment_preference_check;

alter table public.delivery_orders
add constraint delivery_orders_payment_preference_check
check (
  payment_preference is null or
  payment_preference in ('pay_at_pickup', 'pay_on_ready_delivery', 'pay_at_store_pickup')
);

alter table public.delivery_orders
drop constraint if exists delivery_orders_payment_status_check;

alter table public.delivery_orders
add constraint delivery_orders_payment_status_check
check (payment_status in ('unpaid', 'partial', 'paid'));
