-- ========================================================
-- ENDURECIMIENTO DE PRODUCCION PARA DELIVERY
-- ========================================================

alter table public.delivery_orders
drop constraint if exists delivery_orders_status_check;

alter table public.delivery_orders
add constraint delivery_orders_status_check
check (status in ('requested', 'assigned', 'picked_up', 'delivered_to_store', 'completed', 'cancelled'));

create index if not exists idx_delivery_orders_user_status
on public.delivery_orders(user_id, status);

create index if not exists idx_delivery_orders_driver_status
on public.delivery_orders(driver_id, status);

create index if not exists idx_delivery_orders_tracking_token
on public.delivery_orders(tracking_token);

create index if not exists idx_delivery_payments_order_status
on public.delivery_payments(delivery_order_id, status);

create table if not exists public.delivery_notification_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade,
  delivery_order_id bigint references public.delivery_orders(id) on delete cascade,
  recipient_type text not null check (recipient_type in ('customer', 'driver')),
  recipient_phone text,
  event_type text not null,
  gateway text,
  success boolean not null default false,
  error text,
  sent_to text,
  payload jsonb,
  created_at timestamptz not null default timezone('utc'::text, now())
);

alter table public.delivery_notification_logs enable row level security;

drop policy if exists "Stores can read own delivery notification logs" on public.delivery_notification_logs;
create policy "Stores can read own delivery notification logs"
on public.delivery_notification_logs
for select
to authenticated
using (auth.uid() = user_id);

create index if not exists idx_delivery_notification_logs_order
on public.delivery_notification_logs(delivery_order_id, created_at desc);

-- Evidencia privada: el cliente autenticado solo puede escribir/leer su propio prefijo.
drop policy if exists "Authenticated users can upload delivery evidence" on storage.objects;
drop policy if exists "Authenticated users can read delivery evidence" on storage.objects;
drop policy if exists "Authenticated users can update delivery evidence" on storage.objects;
drop policy if exists "Stores can upload own delivery evidence" on storage.objects;
drop policy if exists "Stores can read own delivery evidence" on storage.objects;
drop policy if exists "Stores can update own delivery evidence" on storage.objects;

create policy "Stores can upload own delivery evidence"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'delivery-evidence'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "Stores can read own delivery evidence"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'delivery-evidence'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "Stores can update own delivery evidence"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'delivery-evidence'
  and (storage.foldername(name))[1] = auth.uid()::text
)
with check (
  bucket_id = 'delivery-evidence'
  and (storage.foldername(name))[1] = auth.uid()::text
);

-- Compatibilidad: corregir customer_id uuid -> bigint solo si no hay datos.
do $$
declare
  v_delivery_customer_type text;
  v_customer_id_type text;
  v_non_null_rows integer;
begin
  select c.udt_name into v_delivery_customer_type
  from information_schema.columns c
  where c.table_schema = 'public'
    and c.table_name = 'delivery_orders'
    and c.column_name = 'customer_id';

  select c.udt_name into v_customer_id_type
  from information_schema.columns c
  where c.table_schema = 'public'
    and c.table_name = 'customers'
    and c.column_name = 'id';

  if v_delivery_customer_type = 'uuid' and v_customer_id_type = 'int8' then
    execute 'select count(*) from public.delivery_orders where customer_id is not null'
    into v_non_null_rows;

    if v_non_null_rows = 0 then
      alter table public.delivery_orders
      drop constraint if exists delivery_orders_customer_id_fkey;

      alter table public.delivery_orders
      alter column customer_id type bigint using null::bigint;

      alter table public.delivery_orders
      add constraint delivery_orders_customer_id_fkey
      foreign key (customer_id) references public.customers(id) on delete set null;
    else
      raise notice 'delivery_orders.customer_id es uuid con datos no nulos; no se altero automaticamente.';
    end if;
  end if;
end $$;
