name: Build and Release

on:
  push:
    tags:
      - "v*" # Se activa cuando creas un tag que empieza con 'v' (ej: v1.3.1)

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install root dependencies
        run: npm install

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build and Publish Electron App
        run: npm run electron:build -- --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VITE_SUPABASE_URL: "https://jugyosyrbixwsmzvdksp.supabase.co"
          VITE_SUPABASE_ANON_KEY: "sb_publishable_pkUlkLzd6rPbvG9dD4usPg_qALhsbSd"
